---
title: "Rapporteket, generell informasjon"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rapporteket, generell informasjon}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# RAPPORTEKET

Rapporteket er en elektronisk resultattjeneste som er tilgjengelig for medisinske kvalitetsregistre
Tjenesten viser oppdaterte resultater fra registeret og datagrunnlaget oppdateres daglig.
Gjennom Rapporteket kan hver registrerende avdeling se egne resultater og sammenligne med resten av landet. Man kan også benytte resultater fra Rapporteket til videre formidling av resultater.

 
## Innhold
Rapporteket er en on-line resultattjeneste som i 2024 nås gjennom pålogging fra helseregister.no. I løpet av 2025 vil tjenesten være flyttet til samme portal som registrets innregistreringsløsning slik at pålogging da vil skje gjennom FALK. Rapporteket kan benyttes uavhengig av registrets innregistreringsløsning. Rapporteket er bygd opp ved hjelp av  statistikkprogrammet R og webpubliseringsverktøyet R-Shiny.  All programvare er basert på åpen kildekode. R-koden som danner grunlaget for registerets Rapporteket-applikasjon, finnes på https://github.com/Rapporteket. Hvert register har sin egen Rapporteket-applikasjon og all aktivitet logges. 

Resultatene genereres på grunnlag av data tilgjengelig fra Registerets database. 
Det betyr at når man skal lage automatisk genererte resultater som figurer og tabeller, må man ta høyde for at datagrunnlaget er dynamisk (dvs. i stadig endring).


Resultater vil i denne sammenheng først og fremst være figurer og tabeller som oppsummerer data hentet fra registerets datakilde. Det kan også være ferdige rapporter i form av et dokument med figurer, tabeller, analyser og tekst (prosa). Rapporter kan settes opp til å sendes ut regelmessig  på e-post.

_Eksempler på resultater, visualiseringer og funksjonalitet Rapporteket-applikasjonen til et register kan inneholde:_

* Figurer hvor man kan gjøre ulike datautvalg, eksempelvis fordeling av en variabel, utvikling over tid (per måned/år) eller figurer som sammenligner resultater fra hvert av sykehusene. 
* Registreringsoversikter, status
* Tabelloversikter, nøkkeltall
* Dashboard - samling/sammenstilling av oppdatert nøkkelinforasjon for registeret på én side.
* Samlerapport med figurer/tabeller og tekst som brukeren kan laste ned fra Rapporteket eller få tilsendt på e-post. Registeret  definerer innholdet i samlerapporten (figurer, tabeller, analyser og tekst), hvilket utvalg rapporten skal gjelde og hvor ofte den skal sendes ut. Rapporten er til en hver tid oppdatert med alle data som er overført til Rapportekets database.  


## Bestilling
Hvis du ønsker å bestille Rapporteket for ditt register er første steg å ta kontakt med Nasjonale Servicemiljø eller Servicemiljøet i din region. Servicemiljøet vil bistå registeret med videre bestilling. Spørsmål kan også rettes til rapporteket@skde.no. 

For å kunne jobbe med et register, er det viktig at det finnes en detaljert variabeldokumentasjon av alle variable i registeret, at registeret kan formidle hva de ønsker å finne på Rapporteket for det aktuelle registeret (bestilling), Dette innebærer å spesifisere hvilke type figurer og tabeller man ønsker, samt hvilke variable som skal visualiseres.

Når det konkrete arbeidet starter, er det viktig at det er en faglig kontaktperson i registeret er tilgjengelig for spørsmål, avklaringer og diskusjon.

Vi vil være behjelpelige med å komme fram endelig utforming av figurer, tabeller og rapporter. Avhengig av hvordan man blir enige om å dele opparbeidet, vil hele eller deler av resultattjenesten vil komme i testversjon ei stund etter ”fysisk” oppstart. Det er da viktig at noen fra registeret aktivt bruker testversjon, setter seg inn i hvordan systemet fungerer, bruker dataene kritisk og kommer med tilbakemeldig på mulige feil og eventuelle misforståleser mht. funksjonalitet. Det er viktig å være klar over at statistikeren ikke har medisinsk kompetanse og følgelig ikke har noe grunnlag for å vurdere om et resultat ser vettig ut.

Det er registeret som definerer hvilke resultater/visualiseringer de ønsker å finne på Rapporteket. En bestilling av Rapporteket må minst inneholde følgende informasjon:

* Dokumentasjon av variable, dvs. variabelnavn i innregistreringsskjema, hvilket navn variabelen har i databasen, hvilke verdier en variabel kan ha (koder og tekst), dataformat (tekst, numerisk, dato, osv.) og avhengigheter mellom variablene. En korrekt kodebok vil kunne gi svar på mye av dette. Hvordan variablene henger sammen, dvs. hvordan de eventuelt er innbyrdes avhengige, samt hvordan ulike tabeller skal kobles sammen, må også registeret kunne formidle informasjon om.
* Kontaktperson(er) – Det er viktig at denne personen er tilgjengelig og kan respondere på henvendelser relativt raskt, særlig i perioder hvor man har avtalt at det skal jobbes med registeret.
* Bestilling med spesifikasjon (gjerne ei tegning) av hvilke figurer man ønsker, samt hvilke variabler som skal framstilles med denne type figur. Det må også spesifiseres hva man ønsker å kunne filtrere resultatene på, f.eks. tidsperiode, kjønn, alder, diagnose, osv..  Det er svært viktig at registeret tenker gjennom hva slags informasjon som er viktig og kan oppgi forutsetninger som ligger til grunn. (F.eks. om man skal utelate pasienter som er overført til andre sykehus ved beregning av liggetid.).
* Spesifikasjonene må være konkrete. Skal man ha statistiske mål (gjennomsnitt, sd, osv.) eller andeler? Skal andel beregnes med eller uten ukjente? Er noen variable bare aktuelle å vise for et gitt utvalg av en annen variabel? Hvordan skal variablene grupperes i ulike tabeller eller figurer? Hvilke utvalg skal det være mulig å gjøre?
*Registeret kan velge en egen fargepalett for sine figurer. Alternativt får man en palett med blåfarger, samt grått og rødt valgt fra "offentliggjøringspaletten".
(Et bestillingskjema for noen av figurtypene som tilbys på rapporteket og en beskrivelse av hvordan bestilling kan spesifiseres finner du her: [lenker til et regneark] - MÅ SE OM DETTE REGNEARKET FORTSATT ER MULIG Å FINNE...)



## Kostnader
Utvikling av innhold vil fortrinnsvis utføres av en statistiker i Servicemiljøet eller hos registeret og således ikke kreve ekstra kostnader i form av penger. Men ikke undervurder at det kreves kostnader i form av tid og engasjement fra registeret. Slike kostnader vil avhenge av registerets kompleksitet og hvor omfattende resultattjeneste man ønsker. 

Når Rapporteket settes i produksjon, påløper det en fast årlig driftsutgift til Norsk Helsenett.
