---
title: "Rapporteket, hva, hvorfor, hvordan?"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rapporteket, hva, hvorfor, hvordan?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Vi trenger å lage informasjon om Rapporteket, fortrinnsvis til registrene.
Lenke fra kvalitetsregistre.no til ei side vi selv holder oppdatert? Lenke inn en Shiny-applikasjon som eksempel

## Videre plan
Are lager en pakke som har "all" informasjon om Rapporteket. Denne skal inneholde
informasjon som direkte kan brukes på ei nettside, dvs. lenkes inn på kvalitetsregistre.no. Oppgaver/hvem som skriver de ulike informasjonsdelene  spesifiseres.


### Hvorfor trenger mitt register Rapporteket?
For å få tilgang til kontinuerlig oppdaterte resultater, potensielt for alle variable.
Hvis man skal registrere data, er det viktig å kunne få noe tilbake i form av oppdaterte resultater. Alle avdelinger som registrerer vil kunne gå inn på Rapporteket å se på sine resultater. Registeret definerer selv hva det skal være mulighet for å se på sitt Rapportek.
Gjennom Rapporteket kan hver registrerende avdeling se egne resultater og sammenligne med resten av landet. På denne måten kan man lære av hverandres erfaringer. 

### Trenger jeg Rapporteket når jeg har Resultatportalen?
Ja. 
På Resultatportalen er det anonymiserte data som ligger til grunn for visningene og det er fortrinnsvis resultater fra kvalitetsindikatorer som vises. På Rapporteket kan man i prinsippet lage resultater for alle variable og vise de resultatene man ønsker. Data i Resultatportalen oppdateres så ofte man ønsker, men det skjer, per i dag, manuelt. Data i Rapporteket oppdateres daglig.

### Hva kan Rapporteket levere?
* Figurer og tabeller, samt nedlasting av disse
* Dashbord
* Pre-definerte rapporter (ferdige dokumenter med oppdaterte resultater).
* Regelmessig (automatisk) utsending av rapporter.


### Hvordan går jeg fram for å få Rapporteket?
Kontakte Are Edvardsen (e-post). Videre prosess blir å avklare hvem som skal utvikle innhold på Rapporteket for registeret. Fortrinnsvis er dette statistiker i egen region eller i registeret.

### Er Rapporteket bare for QReg-registre?
Nei.
Har man Qreg er per i dag dataoverføring lett å få til. For MRS-registre er det 
ikke en permanent løsning på plass, men det jobbes med saken. Fra andre innregistreringsløsninger 
er det så langt ikke gjort dataoverføring, men ikke la det hindre deg i å ta kontakt! Det skal være mulig å få Rapporteket uansett hvilken innregistreringsløsning du har.  


### Hvor mye arbeid/tid/ressurser vil det kreve fra registeret for å få på plass Rapporteket?
Det kommer an på hvor mye man ønsker å vise på Rapporteket og hvor komplektst registeret er.
Jo mer innhold og jo høyere kompleksitet, desto mer tid og involvering krever dette fra registeret. 
Spesifikt kan nevnes at hver gang man gjør ei oppdatering/endring av sin innregistreringsløsning, vil det kreves at man har en grundig sjekk av resultater på Rapporteket siden endringene i de aller fleste tilfeller, krever tilpasning av koden på Rapporteket.


Fordeler
Ulemper: Må logge inn. Krever egeninnsats 


# Fra nettsidene: RAPPORTEKET
*Oppdatring startet, må oppdateres ytterligere*

Det er et overordnet mål for norsk helsevesen at pasientene skal få lik og like god behandling. 
Skal vi oppnå dette, trengs det solid kunnskap om utredning, behandling og oppfølging for ulike sykdommer. Medisinske kvalitetsregistre gir oss slik kunnskap. For at vi skal lære av hverandres erfaringer er det imidlertid avgjørende at kunnskapen deles. Nasjonalt servicemiljø for medisinske kvalitetsregistre ser det som en prioritert oppgave å bidra til at resultater fra registre blir gjort tilgjengelig.

Rapporteket er en elektronisk resultattjeneste som inneholder daglig oppdaterte resultater fra registeret. Tjenesten er tilgjengelig for medisinske kvalitetsregistre. 
Gjennom Rapporteket kan hver registrerende avdeling se egne resultater og sammenligne med resten av landet. Man kan også benytte resultater fra Rapporteket til videre deling av resultater.

 
## Innhold
Rapporteket er en on-line resultattjeneste som nås gjennom samme portal som registrets innregistreringsløsning. Den er en frittstående ressurs som henter data fra andre kilder. Det betyr at resultattjenesten kan benyttes uavhengig av registrets innregistreringsløsning. All aktivitet logges. All programvare er basert på åpen kildekode. Rapporteket er bygd opp ved hjelp av  statistikkprogrammet R og webpubliseringsverktøyet R-Shiny. 

Resultatene genereres på grunnlag av all tilgjengelig informasjon i Registerets database. Det betyr at når man skal lage «rapporter» må man ta høyde for at datagrunnlaget er dynamisk (dvs. i stadig endring).

Begrepet «rapport» er noe diffust, men det omfatter i denne sammenheng først og fremst figurer og tabeller som oppsummerer data hentet direkte fra registerets datakilde. En rapport kan også være ei sammenstilling av figurer og/eller tabeller som presenteres i nettleseren eller som et pdf-dokument. En rapport kan også være det man vanligvis tenker på som en rapport, nemlig et dokument med både figurer, tabeller, analyser og tekst (prosa). Rapporter kan settes opp til å sendes ut regelmessig  på e-post.

_Eksempler på hvilke resultater man kan ha på Rapporteket:_
* Forhåndsdefinerte figurer hvor man kan gjøre ulike datautvalg, eksempelvis fordelingsfigurer eller figurer som sammenligner resultater fra hvert av sykehusene. 
* Samlerapport med figurer/tabeller og tekst som brukeren ber om i Rapporteket og får tilsendt på e-post. Registeret må definere innholdet i samlerapporten (figurer, tabeller, analyser og tekst), hvilket utvalg rapporten skal gjelde og hvor ofte den skal sendes ut. Alle tall i rapporten er basert på alle data som er registret inn i databasen.  


Det er registeret som definerer hvilke resultater/visualiseringer de ønsker å finne på Rapporteket. En bestilling av Rapporteket må minst inneholde følgende informasjon:

* Dokumentasjon av variable, dvs. variabelnavn i innregistreringsskjema, hvilket navn variabelen har i databasen, hvilke verdier en variabel kan ha (koder og tekst), dataformat (tekst, numerisk, dato, osv.) og avhengigheter mellom variablene. En korrekt kodebok vil kunne gi svar på mye av dette. Hvordan variablene henger sammen, dvs. hvordan de eventuelt er innbyrdes avhengige, samt hvordan ulike tabeller skal kobles sammen, må også registeret kunne gjøre rede for.
* Kontaktperson(er) – Det er viktig at denne personen faktisk er tilgjengelig og kan respondere på henvendelser relativt raskt i perioden vi jobber med registeret. Tidsrom hvor man trenger tettere kontakt avtales.
* Bestilling med spesifikasjon (gjerne ei tegning) av hvilke figurer man ønsker, samt hvilke variable som skal framstilles med denne type figur. Det må også spesifiseres hva man ønsker å kunne filtrere resultatene på, f.eks. tidsperiode, kjønn, alder, diagnose, osv..  Det er svært viktig at registeret tenker gjennom hva slags informasjon som er viktig og kan oppgi forutsetninger som ligger til grunn. (F.eks. om man skal utelate pasienter som er overført til andre sykehus ved beregning av liggetid.).
* Nøyaktig spesifikasjon av tabeller. Skal man ha statistiske mål (gjennomsnitt, sd, osv.) eller andeler. Skal andel beregnes med eller uten ukjente? Er noen variable bare aktuelle å vise for et gitt utvalg av en annen variabel? Hvordan skal variablene grupperes i ulike tabeller? Hvilke utvalg skal det være mulig å gjøre i tabellene?
*Registeret har mulighet til å velge registerspesifikk fargepalett for sine figurer. (Alternativt får man en palett med fire blåfarger valgt fra "offentliggjøringspaletten".)
Et bestillingskjema for noen av figurtypene som tilbys på rapporteket og en beskrivelse av hvordan bestilling kan spesifiseres finner du her: [lenker til et regneark]

## Bestilling
Hvis du ønsker å bestille Rapporteket for ditt register er første steg å ta kontakt med det Nasjonale Servicemiljøet ved Are Edvardsen (are.edvardsen@skde.no), alternativt rapporteket@skde.no. Servicemiljøet vil bistå registeret med videre bestilling.

For å kunne jobbe med et register, er det viktig at det finnes en detaljert  variabeldokumentasjon av alle variable i registeret  kan formidle hva de ønsker å finne på regsiteret (bestilling), samt at variabeldokumentasjon og gi ei bestilling av hvilke figurer og tabeller man ønsker, samt hvilke variable som skal visualiseres.

Når det konkrete arbeidet starter, er det viktig at det er en faglig kontaktperson i registeret er tilgjengelig for spørsmål, avklaringer og diskusjon.

Vi vil være behjelpelige med å komme fram endelig utforming av figur/tabell. Avhengig av hvordan man blir enige om å dele opparbeidet, vil hele eller deler av resultattjenesten vil komme i testversjon ei stund etter ”fysisk” oppstart. Det er da viktig at noen fra registeret aktivt bruker testversjon, setter seg inn i hvordan systemet fungerer, bruker dataene kritisk og kommer med tilbakemeldig på mulige feil og eventuelle misforståleser mht. funksjonalitet.

## Kostnader
Utvikling av innhold vil fortrinnsvis utføres av en statistiker i Servicemiljøet eller hos registeret og således ikke kreve ekstra kostnader i form av penger. Men ikke undervurder at det kreves kostnader i form av tid og engasjement fra registeret. Slike kostnader vil avhenge av registerets kompleksitet og hvor omfattende resultattjeneste man ønsker. 

Når Rapporteket settes i produksjon, påløper det en fast årlig driftsutgift til Norsk Helsenett.
