---
title: "Kort om Rapporteket"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Kort om Rapporteket}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

*Rapporteket* er en analyse- og rapporteringstjenste som benyttes av medisinske kvalitetsregistre. Formålet med slike registre er å overvåke kvalitet og bidra til kvalitetsforbedring i helsetjenesten. Med utgangspunkt i data fra registrene kan *Rapporteket* tilby interaktiv undersøkelse av rådata, rutinemessig utsending av rapporter og visualisering av resultater fra registrene. Tjenesten utvikles og vedlikeholdes av [Nasjonalt servicemiljø for medisinske kvalitetsregistre](https://www.kvalitetsregistre.no/) ved [Senter for Klinisk Dokumentasjon og Evaluering (SKDE)](https://helse-nord.no/skde) og arbeidet finansieres av [Helse- og omsorgsdepartementet](https://www.regjeringen.no/no/dep/hod/id421/).

Teknologien bak *Rapporteket* er i hovedsak basert på [R](https://www.r-project.org/) som er et [fritt tilgjengelig](https://www.gnu.org/philosophy/free-sw.html) programvaremiljø for statistiske og grafiske formål. All programkode og annet innhold (utenom registerdata) på *Rapporteket* er strukturert i [R-pakker som lages og vedlikeholdes av statistikere i registrene](https://github.com/Rapporteket).
